#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0 constant/polyMesh

cp -r zero.cyclic 0

runApplication blockMesh

runApplication createPatch -overwrite

for i in 1 2 3
do
    runApplication -s $i \
        topoSet -dict system/topoSetDict.${i}

    runApplication -s $i \
        refineMesh -dict system/refineMeshDict -overwrite
done

runApplication setFields

runApplication decomposePar

runParallel $(getApplication)
#runApplication $(getApplication)

#------------------------------------------------------------------------------
